version: "3.3"
services:
  db:
    image: postgres:12
    user: 1000:1000
    volumes:
      - ./backend/data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    user: 1000:1000
    depends_on:
      - db
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    ports:
      - 8000:80
    build:
      context: ./backend
      dockerfile: Backend.dockerfile