"""First migration

Revision ID: 3d69b2782d85
Revises: 
Create Date: 2021-03-02 13:54:35.969613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d69b2782d85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_form_event_organization_dateFinish', table_name='form_event_organization')
    op.drop_index('ix_form_event_organization_dateStart', table_name='form_event_organization')
    op.drop_index('ix_form_event_organization_designation', table_name='form_event_organization')
    op.drop_index('ix_form_event_organization_eventType', table_name='form_event_organization')
    op.drop_index('ix_form_event_organization_involvementType', table_name='form_event_organization')
    op.drop_index('ix_form_event_organization_local', table_name='form_event_organization')
    op.drop_index('ix_form_event_organization_regionType', table_name='form_event_organization')
    op.drop_table('form_event_organization')
    op.drop_table('form_event_organization_members')
    op.drop_index('ix_form_event_participation_dateFinish', table_name='form_event_participation')
    op.drop_index('ix_form_event_participation_dateStart', table_name='form_event_participation')
    op.drop_index('ix_form_event_participation_event', table_name='form_event_participation')
    op.drop_index('ix_form_event_participation_eventType', table_name='form_event_participation')
    op.drop_index('ix_form_event_participation_local', table_name='form_event_participation')
    op.drop_index('ix_form_event_participation_participationType', table_name='form_event_participation')
    op.drop_index('ix_form_event_participation_title', table_name='form_event_participation')
    op.drop_table('form_event_participation')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_export_schemas_name', table_name='export_schemas')
    op.drop_index('ix_export_schemas_type', table_name='export_schemas')
    op.drop_table('export_schemas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_schemas',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('userId', sa.CHAR(length=36), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('template', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_schemas_type', 'export_schemas', ['type'], unique=False)
    op.create_index('ix_export_schemas_name', 'export_schemas', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=72), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.CheckConstraint('is_active IN (0, 1)'),
    sa.CheckConstraint('is_superuser IN (0, 1)'),
    sa.CheckConstraint('is_verified IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.create_table('form_event_participation',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('userId', sa.CHAR(length=36), nullable=True),
    sa.Column('eventType', sa.VARCHAR(length=64), nullable=False),
    sa.Column('participationType', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('event', sa.VARCHAR(length=64), nullable=False),
    sa.Column('local', sa.VARCHAR(length=64), nullable=False),
    sa.Column('dateStart', sa.DATE(), nullable=False),
    sa.Column('dateFinish', sa.DATE(), nullable=False),
    sa.Column('observations', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_form_event_participation_title', 'form_event_participation', ['title'], unique=False)
    op.create_index('ix_form_event_participation_participationType', 'form_event_participation', ['participationType'], unique=False)
    op.create_index('ix_form_event_participation_local', 'form_event_participation', ['local'], unique=False)
    op.create_index('ix_form_event_participation_eventType', 'form_event_participation', ['eventType'], unique=False)
    op.create_index('ix_form_event_participation_event', 'form_event_participation', ['event'], unique=False)
    op.create_index('ix_form_event_participation_dateStart', 'form_event_participation', ['dateStart'], unique=False)
    op.create_index('ix_form_event_participation_dateFinish', 'form_event_participation', ['dateFinish'], unique=False)
    op.create_table('form_event_organization_members',
    sa.Column('member_id', sa.CHAR(length=36), nullable=False),
    sa.Column('form_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form_event_organization.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'form_id')
    )
    op.create_table('form_event_organization',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('eventType', sa.VARCHAR(length=64), nullable=False),
    sa.Column('involvementType', sa.VARCHAR(length=64), nullable=False),
    sa.Column('regionType', sa.VARCHAR(length=64), nullable=False),
    sa.Column('designation', sa.VARCHAR(length=64), nullable=False),
    sa.Column('local', sa.VARCHAR(length=64), nullable=False),
    sa.Column('dateStart', sa.DATE(), nullable=False),
    sa.Column('dateFinish', sa.DATE(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('observations', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('userId', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_form_event_organization_regionType', 'form_event_organization', ['regionType'], unique=False)
    op.create_index('ix_form_event_organization_local', 'form_event_organization', ['local'], unique=False)
    op.create_index('ix_form_event_organization_involvementType', 'form_event_organization', ['involvementType'], unique=False)
    op.create_index('ix_form_event_organization_eventType', 'form_event_organization', ['eventType'], unique=False)
    op.create_index('ix_form_event_organization_designation', 'form_event_organization', ['designation'], unique=False)
    op.create_index('ix_form_event_organization_dateStart', 'form_event_organization', ['dateStart'], unique=False)
    op.create_index('ix_form_event_organization_dateFinish', 'form_event_organization', ['dateFinish'], unique=False)
    # ### end Alembic commands ###
