"""First migration

Revision ID: 58dd404deabb
Revises: 3d69b2782d85
Create Date: 2021-03-02 14:01:40.888804

"""
import fastapi_users
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dd404deabb'
down_revision = '3d69b2782d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=72), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('export_schemas',
    sa.Column('id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('userId', fastapi_users.db.sqlalchemy.GUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_schemas_name'), 'export_schemas', ['name'], unique=False)
    op.create_index(op.f('ix_export_schemas_type'), 'export_schemas', ['type'], unique=False)
    op.create_table('form_event_organization',
    sa.Column('id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('eventType', sa.String(length=64), nullable=False),
    sa.Column('involvementType', sa.String(length=64), nullable=False),
    sa.Column('regionType', sa.String(length=64), nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('local', sa.String(length=64), nullable=False),
    sa.Column('dateStart', sa.Date(), nullable=False),
    sa.Column('dateFinish', sa.Date(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('userId', fastapi_users.db.sqlalchemy.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_event_organization_dateFinish'), 'form_event_organization', ['dateFinish'], unique=False)
    op.create_index(op.f('ix_form_event_organization_dateStart'), 'form_event_organization', ['dateStart'], unique=False)
    op.create_index(op.f('ix_form_event_organization_designation'), 'form_event_organization', ['designation'], unique=False)
    op.create_index(op.f('ix_form_event_organization_eventType'), 'form_event_organization', ['eventType'], unique=False)
    op.create_index(op.f('ix_form_event_organization_involvementType'), 'form_event_organization', ['involvementType'], unique=False)
    op.create_index(op.f('ix_form_event_organization_local'), 'form_event_organization', ['local'], unique=False)
    op.create_index(op.f('ix_form_event_organization_regionType'), 'form_event_organization', ['regionType'], unique=False)
    op.create_table('form_event_participation',
    sa.Column('id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('eventType', sa.String(length=64), nullable=False),
    sa.Column('participationType', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('local', sa.String(length=64), nullable=False),
    sa.Column('dateStart', sa.Date(), nullable=False),
    sa.Column('dateFinish', sa.Date(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('userId', fastapi_users.db.sqlalchemy.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_event_participation_dateFinish'), 'form_event_participation', ['dateFinish'], unique=False)
    op.create_index(op.f('ix_form_event_participation_dateStart'), 'form_event_participation', ['dateStart'], unique=False)
    op.create_index(op.f('ix_form_event_participation_event'), 'form_event_participation', ['event'], unique=False)
    op.create_index(op.f('ix_form_event_participation_eventType'), 'form_event_participation', ['eventType'], unique=False)
    op.create_index(op.f('ix_form_event_participation_local'), 'form_event_participation', ['local'], unique=False)
    op.create_index(op.f('ix_form_event_participation_participationType'), 'form_event_participation', ['participationType'], unique=False)
    op.create_index(op.f('ix_form_event_participation_title'), 'form_event_participation', ['title'], unique=False)
    op.create_table('form_event_organization_members',
    sa.Column('member_id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('form_id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form_event_organization.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'form_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_event_organization_members')
    op.drop_index(op.f('ix_form_event_participation_title'), table_name='form_event_participation')
    op.drop_index(op.f('ix_form_event_participation_participationType'), table_name='form_event_participation')
    op.drop_index(op.f('ix_form_event_participation_local'), table_name='form_event_participation')
    op.drop_index(op.f('ix_form_event_participation_eventType'), table_name='form_event_participation')
    op.drop_index(op.f('ix_form_event_participation_event'), table_name='form_event_participation')
    op.drop_index(op.f('ix_form_event_participation_dateStart'), table_name='form_event_participation')
    op.drop_index(op.f('ix_form_event_participation_dateFinish'), table_name='form_event_participation')
    op.drop_table('form_event_participation')
    op.drop_index(op.f('ix_form_event_organization_regionType'), table_name='form_event_organization')
    op.drop_index(op.f('ix_form_event_organization_local'), table_name='form_event_organization')
    op.drop_index(op.f('ix_form_event_organization_involvementType'), table_name='form_event_organization')
    op.drop_index(op.f('ix_form_event_organization_eventType'), table_name='form_event_organization')
    op.drop_index(op.f('ix_form_event_organization_designation'), table_name='form_event_organization')
    op.drop_index(op.f('ix_form_event_organization_dateStart'), table_name='form_event_organization')
    op.drop_index(op.f('ix_form_event_organization_dateFinish'), table_name='form_event_organization')
    op.drop_table('form_event_organization')
    op.drop_index(op.f('ix_export_schemas_type'), table_name='export_schemas')
    op.drop_index(op.f('ix_export_schemas_name'), table_name='export_schemas')
    op.drop_table('export_schemas')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
