"""Added refeering editorial act table

Revision ID: 06929527b53e
Revises: 6a40a2fb60b4
Create Date: 2021-03-06 19:32:02.399514

"""
import fastapi_users
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06929527b53e'
down_revision = '6a40a2fb60b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_referring_editorial_act',
    sa.Column('id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('memberId', fastapi_users.db.sqlalchemy.GUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('regionType', sa.String(length=64), nullable=False),
    sa.Column('publicationType', sa.String(length=64), nullable=False),
    sa.Column('publication', sa.String(length=256), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('userId', fastapi_users.db.sqlalchemy.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_referring_editorial_act_publication'), 'form_referring_editorial_act', ['publication'], unique=False)
    op.create_index(op.f('ix_form_referring_editorial_act_publicationType'), 'form_referring_editorial_act', ['publicationType'], unique=False)
    op.create_index(op.f('ix_form_referring_editorial_act_regionType'), 'form_referring_editorial_act', ['regionType'], unique=False)
    op.create_index(op.f('ix_form_referring_editorial_act_reviews'), 'form_referring_editorial_act', ['reviews'], unique=False)
    op.create_index(op.f('ix_form_referring_editorial_act_type'), 'form_referring_editorial_act', ['type'], unique=False)
    op.create_index(op.f('ix_form_referring_editorial_act_year'), 'form_referring_editorial_act', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_referring_editorial_act_year'), table_name='form_referring_editorial_act')
    op.drop_index(op.f('ix_form_referring_editorial_act_type'), table_name='form_referring_editorial_act')
    op.drop_index(op.f('ix_form_referring_editorial_act_reviews'), table_name='form_referring_editorial_act')
    op.drop_index(op.f('ix_form_referring_editorial_act_regionType'), table_name='form_referring_editorial_act')
    op.drop_index(op.f('ix_form_referring_editorial_act_publicationType'), table_name='form_referring_editorial_act')
    op.drop_index(op.f('ix_form_referring_editorial_act_publication'), table_name='form_referring_editorial_act')
    op.drop_table('form_referring_editorial_act')
    # ### end Alembic commands ###
