"""Added schema extension

Revision ID: 10f3d38dd56d
Revises: a59f38a54b57
Create Date: 2021-03-02 18:31:58.312929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f3d38dd56d'
down_revision = 'a59f38a54b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_schemas', sa.Column('extension', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_export_schemas_extension'), 'export_schemas', ['extension'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_schemas_extension'), table_name='export_schemas')
    op.drop_column('export_schemas', 'extension')
    # ### end Alembic commands ###
