"""Added supervision form

Revision ID: 23e4d8a8bb12
Revises: 650540eca0b2
Create Date: 2021-03-02 19:47:07.290860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e4d8a8bb12'
down_revision = '650540eca0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
