"""Modified extension form description column

Revision ID: 650540eca0b2
Revises: b6f57030f184
Create Date: 2021-03-02 19:09:02.732807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650540eca0b2'
down_revision = 'b6f57030f184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_form_extension_description', table_name='form_extension')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_form_extension_description', 'form_extension', ['description'], unique=False)
    # ### end Alembic commands ###
