"""Added jury scientific committee table

Revision ID: 6a40a2fb60b4
Revises: 23e4d8a8bb12
Create Date: 2021-03-06 17:56:39.173178

"""
import fastapi_users
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a40a2fb60b4'
down_revision = '23e4d8a8bb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_jury_scientific_committee',
    sa.Column('id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('memberId', fastapi_users.db.sqlalchemy.GUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('dateStart', sa.Date(), nullable=False),
    sa.Column('dateFinish', sa.Date(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('userId', fastapi_users.db.sqlalchemy.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_jury_scientific_committee_dateFinish'), 'form_jury_scientific_committee', ['dateFinish'], unique=False)
    op.create_index(op.f('ix_form_jury_scientific_committee_dateStart'), 'form_jury_scientific_committee', ['dateStart'], unique=False)
    op.create_index(op.f('ix_form_jury_scientific_committee_description'), 'form_jury_scientific_committee', ['description'], unique=False)
    op.create_index(op.f('ix_form_jury_scientific_committee_type'), 'form_jury_scientific_committee', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_jury_scientific_committee_type'), table_name='form_jury_scientific_committee')
    op.drop_index(op.f('ix_form_jury_scientific_committee_description'), table_name='form_jury_scientific_committee')
    op.drop_index(op.f('ix_form_jury_scientific_committee_dateStart'), table_name='form_jury_scientific_committee')
    op.drop_index(op.f('ix_form_jury_scientific_committee_dateFinish'), table_name='form_jury_scientific_committee')
    op.drop_table('form_jury_scientific_committee')
    # ### end Alembic commands ###
