"""Added extension form

Revision ID: b6f57030f184
Revises: 10f3d38dd56d
Create Date: 2021-03-02 19:06:52.960252

"""
import fastapi_users
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f57030f184'
down_revision = '10f3d38dd56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_extension',
    sa.Column('id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('dateStart', sa.Date(), nullable=False),
    sa.Column('dateFinish', sa.Date(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('userId', fastapi_users.db.sqlalchemy.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_extension_dateFinish'), 'form_extension', ['dateFinish'], unique=False)
    op.create_index(op.f('ix_form_extension_dateStart'), 'form_extension', ['dateStart'], unique=False)
    op.create_index(op.f('ix_form_extension_description'), 'form_extension', ['description'], unique=False)
    op.create_index(op.f('ix_form_extension_type'), 'form_extension', ['type'], unique=False)
    op.create_table('form_extension_members',
    sa.Column('member_id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.Column('form_id', fastapi_users.db.sqlalchemy.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form_extension.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'form_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_extension_members')
    op.drop_index(op.f('ix_form_extension_type'), table_name='form_extension')
    op.drop_index(op.f('ix_form_extension_description'), table_name='form_extension')
    op.drop_index(op.f('ix_form_extension_dateStart'), table_name='form_extension')
    op.drop_index(op.f('ix_form_extension_dateFinish'), table_name='form_extension')
    op.drop_table('form_extension')
    # ### end Alembic commands ###
