"""Added participants column to EventOrganization Form

Revision ID: cc14db146f84
Revises: 94ae1c1ccdcc
Create Date: 2021-07-02 19:38:09.085086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc14db146f84'
down_revision = '94ae1c1ccdcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_event_organization', sa.Column('participants', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_form_event_organization_participants'), 'form_event_organization', ['participants'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_event_organization_participants'), table_name='form_event_organization')
    op.drop_column('form_event_organization', 'participants')
    # ### end Alembic commands ###
